"""init migration

Revision ID: 121f699a6438
Revises: 
Create Date: 2026-10-05 10:47:40.907791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '121f699a6438'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashsession',
                    sa.Column('session_id', sa.Integer(), nullable=False),
                    sa.Column('opening_balance', sa.Integer(), nullable=False),
                    sa.Column('closing_balance', sa.Integer(), nullable=True),
                    sa.Column('opened_at', sqlmodel.sql.sqltypes.UTCDateTime(),
                              nullable=False),
                    sa.Column('closed_at', sqlmodel.sql.sqltypes.UTCDateTime(),
                              nullable=True),
                    sa.PrimaryKeyConstraint('session_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashsession')
    # ### end Alembic commands ###
