"""adding plan table

Revision ID: 928082d7d1df
Revises: 121f699a6438
Create Date: 2026-10-06 17:05:43.752587

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928082d7d1df'
down_revision: Union[str, Sequence[str], None] = '121f699a6438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
                    sa.Column('plan_id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(
                        length=50), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(
                        length=100), nullable=False),
                    sa.Column('duration', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('plan_id')
                    )
    op.add_column('customer', sa.Column(
        'is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'is_active')
    op.drop_table('plan')
    # ### end Alembic commands ###
